#!/bin/bash
# ============================================
# massa-th0th - Ollama WSL Setup
# ============================================
# Detects the Windows host IP (via eth0 default route, then /etc/resolv.conf)
# and tries to connect to an Ollama instance running on the Windows side.
# Falls back to installing Ollama locally inside WSL if unreachable.
#
# Updates OLLAMA_BASE_URL in the project root .env file.
# ============================================

set -e

# Resolve project root (two levels up from apps/tools-api/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"

# shellcheck source=scripts/banner.sh
source "${PROJECT_ROOT}/scripts/banner.sh"
massa_th0th_banner

info "Detecting environment..."

# shellcheck source=scripts/lib/detect-wsl-ip.sh
source "${PROJECT_ROOT}/scripts/lib/detect-wsl-ip.sh"

WINDOWS_IP=$(detect_wsl_windows_ip) && _detect_method="auto" || _detect_method="failed"

if [ "$_detect_method" = "auto" ]; then
    echo "Windows host IP: ${WINDOWS_IP}"
else
    echo "WARNING: Could not detect Windows host IP automatically."
    read -p "Enter the Windows host IP manually (or press Enter to try localhost): " _manual_ip
    WINDOWS_IP="${_manual_ip:-127.0.0.1}"
fi

# Test connectivity to Ollama running on the Windows host
echo ""
echo "Testing connection to Ollama on Windows..."
if curl -s --connect-timeout 3 "http://${WINDOWS_IP}:11434/api/tags" > /dev/null 2>&1; then
    echo "Connected to Ollama on Windows host."
    OLLAMA_URL="http://${WINDOWS_IP}:11434"
else
    echo "Could not connect to Ollama on Windows (${WINDOWS_IP}:11434)."
    echo ""
    echo "Options:"
    echo "  1. Configure Ollama on Windows to accept external connections."
    echo "     Set OLLAMA_HOST=0.0.0.0 in Windows environment variables, then restart Ollama."
    echo ""
    echo "  2. Install Ollama locally inside WSL."
    read -p "Install Ollama inside WSL? (y/N): " choice

    if [[ "$choice" == "y" || "$choice" == "Y" ]]; then
        echo ""
        echo "Installing Ollama in WSL..."
        curl -fsSL https://ollama.ai/install.sh | sh

        echo ""
        echo "Starting Ollama..."
        ollama serve &
        sleep 5

        echo ""
        echo "Pulling embedding model bge-m3..."
        ollama pull bge-m3

        OLLAMA_URL="http://localhost:11434"
        echo "Ollama installed and running."
    else
        echo ""
        echo "Ollama not configured. Set OLLAMA_BASE_URL manually in .env."
        exit 1
    fi
fi

# Update OLLAMA_BASE_URL in .env (create file if missing)
echo ""
echo "Updating .env at: ${ENV_FILE}"

if [ -f "$ENV_FILE" ]; then
    if grep -q "^OLLAMA_BASE_URL=" "$ENV_FILE"; then
        sed -i "s|^OLLAMA_BASE_URL=.*|OLLAMA_BASE_URL=${OLLAMA_URL}|" "$ENV_FILE"
        echo "Updated OLLAMA_BASE_URL in existing .env."
    else
        echo "OLLAMA_BASE_URL=${OLLAMA_URL}" >> "$ENV_FILE"
        echo "Appended OLLAMA_BASE_URL to existing .env."
    fi
else
    cat > "$ENV_FILE" << EOF
# massa-th0th - Auto-generated by setup-ollama-wsl.sh
OLLAMA_BASE_URL=${OLLAMA_URL}
OLLAMA_EMBEDDING_MODEL=bge-m3
OLLAMA_EMBEDDING_DIMENSIONS=1024

NODE_ENV=development
EOF
    echo "Created .env at ${ENV_FILE}."
fi

# Smoke-test embedding endpoint
echo ""
echo "Testing embedding endpoint..."
if curl -s "${OLLAMA_URL}/api/embeddings" \
    -d '{"model": "bge-m3", "prompt": "test"}' > /dev/null 2>&1; then
    echo "Embeddings working."
else
    echo "Could not reach embedding endpoint. Make sure bge-m3 is pulled:"
    echo "  ollama pull bge-m3"
fi

echo ""
echo "Setup complete. Start the API with:"
echo "  bun run dev:api"
